### ISSUE TITLE
how to create user variable

### ISSUE THREAD

**Issue by salcabo** [kungknut/Domoticz-MQTT-Translator#1]
First of all I'm not programer, so I try to understand but I'm limited.

I create a user variable, type string, copy and paste the code and modify to my needs:

`{
    "MQTT":{
        "devIdx" : 40,
        "inTopic" : "persiana/sta",
        "outTopic" : "persiana/cmnd",
        "slope" : 1,
        "intercept" : 0,
        "limits" : "0,0",
        "type" : "dimmer"
    }
}`

I get error in domoticz: not a valid date notation (DD/MM/YYYY)

Any help will be apreciated

**Comment by kungknut** [comment]
Hi!

By the means of the string you have posted I presume you are trying to send a command to a dimmable light.

Have you configured a dimmer item inside domoticz and have you triggered the node-flow to read the user variables from domoticz?

**Comment by salcabo** [comment]
Not yet, because domoticz does not let me save the string i've atached before as a user variable

**Comment by kungknut** [comment]
Have you set the type of the variable to string?

**Comment by salcabo** [comment]
Yes, variable type string. 

If I copy exactly the code I get error: string is too long. 

If I take out a part (limits), I get error of invalid date.

**Comment by salcabo** [comment]
Sorry about everything, it seems it was a domoticz issue, found the solution and it's working

[https://www.domoticz.com/forum/viewtopic.php?t=27123]

**Comment by kungknut** [comment]
No problem! I'm glad you found a solution to the problem!
